substitutions:
  _IMAGE_NAME: 'agent-search-api'

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${BUILD_ID}',
      '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${BUILD_ID}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_IMAGE_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${BUILD_ID}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'GCP_PROJECT=palate-mvp'

images:
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${BUILD_ID}'
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

